fix login service queries, improve validator

diff --git a/.github/workflows/validate-generated-code.yml b/.github/workflows/validate-generated-code.yml
--- a/.github/workflows/validate-generated-code.yml
+++ b/.github/workflows/validate-generated-code.yml
@@ -46,7 +46,10 @@ jobs:
           done
           cd login-service
           echo "Validating login-service generated code"
-          npm run generate-model
+          if [[ `npm run generate-model` ]]; then
+            echo "Failed to generate model"
+            exit 1
+          fi
           if [[ `git status --porcelain` ]]; then
             echo "Outdated generated code in login-service"
             exit 1
